# Generated by Django 5.2.7 on 2025-11-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('colecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('DANADO', 'Dañado'), ('PERDIDO', 'Perdido')], default='DISPONIBLE', max_length=15)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='catalogo.libro')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejemplares', to='colecciones.ubicacion')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejemplares', to='inventario.ingresoinventario')),
            ],
            options={
                'ordering': ['libro__titulo', 'codigo_barras'],
            },
        ),
        migrations.AddField(
            model_name='ingresoinventario',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='inventario.proveedor'),
        ),
    ]
