# Generated by Django 5.2.7 on 2025-11-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventario.ejemplar')),
                ('empleado_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_entregados', to='personas.empleado')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='personas.socio')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('motivo', models.CharField(max_length=200)),
                ('pagada', models.BooleanField(default=False)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='circulacion.prestamo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('CADUCADA', 'Caducada')], default='PENDIENTE', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='catalogo.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='personas.socio')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
