# Generated by Django 5.2.7 on 2025-11-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('rol', models.CharField(choices=[('BIBLIOTECARIO', 'Bibliotecario'), ('ADMIN', 'Administrador')], default='BIBLIOTECARIO', max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASICA', 'Básica'), ('PREMIUM', 'Premium')], default='BASICA', max_length=10)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='personas.socio')),
            ],
            options={
                'ordering': ['-fin'],
                'constraints': [models.UniqueConstraint(fields=('socio', 'inicio', 'fin'), name='uniq_membresia_rango_por_socio')],
            },
        ),
    ]
